Develop
Noworri/PAL-USER-DASHBOARD pull request #23
Opened 2022-01-10 16:30 UTC by emeric-azonsou

2022-01-10 18:31 UTC, E2dwhy requested changes

2022-01-10 18:31 UTC, E2dwhy commented on src/app/pages/dashboards/disburse-cash/disburse-cash.component.ts
> +  repeatePhoneNumberValidationPattern = /^[0-9]{0,15}$/;
Pourquoi ajouter lles mem valeurs dans une autre variable? tu peu utiliser la variable existante.. cest la meme validation

2022-01-10 18:31 UTC, E2dwhy commented on src/app/pages/dashboards/disburse-cash/disburse-cash.component.ts
> +  phoneCheckError: boolean;
```hasPhoneInputError``` est plus approprie

2022-01-10 18:31 UTC, E2dwhy commented on src/app/pages/dashboards/disburse-cash/disburse-cash.component.ts
> +    console.log(this.transferForm)
n'oublie pas d'enlever console log

2022-01-10 18:31 UTC, E2dwhy commented on src/app/pages/dashboards/disburse-cash/disburse-cash.component.ts
> +  onCheckConformNumber = () => {
faue de frappe  :  ```onCheckConfirmNumber```  au lieu de ```onCheckConformNumber ```

2022-01-10 18:31 UTC, E2dwhy commented on src/app/services/shared-data.service.ts
> +  saveTransferData(transfersData: Object, credential: string) {
Qhelle est l'utilite  de cette classe STP?

2022-01-12 15:03 UTC, emeric-azonsou commented on src/app/services/shared-data.service.ts
> +  saveTransferData(transfersData: Object, credential: string) {
il s'agit dún service qui a pour role le partage de data en deux component(disbuse cash component et confirm transfer component).

2022-01-12 16:31 UTC, E2dwhy approved these changes

2022-01-12 16:31 UTC, merged